/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NeuroMarketV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "STAKE_AMOUNT"
      | "allDatasets"
      | "buyAccess"
      | "getAllDatasets"
      | "listings"
      | "neuroToken"
      | "publishDataset"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DatasetPublished" | "FilePurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "STAKE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allDatasets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDatasets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neuroToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishDataset",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "STAKE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allDatasets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllDatasets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "neuroToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishDataset",
    data: BytesLike
  ): Result;
}

export namespace DatasetPublishedEvent {
  export type InputTuple = [
    dataToken: AddressLike,
    publisher: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    dataToken: string,
    publisher: string,
    price: bigint
  ];
  export interface OutputObject {
    dataToken: string;
    publisher: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FilePurchasedEvent {
  export type InputTuple = [buyer: AddressLike, dataTokenURI: string];
  export type OutputTuple = [buyer: string, dataTokenURI: string];
  export interface OutputObject {
    buyer: string;
    dataTokenURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NeuroMarketV2 extends BaseContract {
  connect(runner?: ContractRunner | null): NeuroMarketV2;
  waitForDeployment(): Promise<this>;

  interface: NeuroMarketV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  STAKE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  allDatasets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  buyAccess: TypedContractMethod<
    [_dataTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllDatasets: TypedContractMethod<[], [string[]], "view">;

  listings: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean, bigint, string] & {
        dataTokenAddress: string;
        publisher: string;
        price: bigint;
        isActive: boolean;
        stakedAmount: bigint;
        ipfsHash: string;
      }
    ],
    "view"
  >;

  neuroToken: TypedContractMethod<[], [string], "view">;

  publishDataset: TypedContractMethod<
    [_ipfsHash: string, _name: string, _symbol: string, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "STAKE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allDatasets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "buyAccess"
  ): TypedContractMethod<
    [_dataTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllDatasets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean, bigint, string] & {
        dataTokenAddress: string;
        publisher: string;
        price: bigint;
        isActive: boolean;
        stakedAmount: bigint;
        ipfsHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "neuroToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishDataset"
  ): TypedContractMethod<
    [_ipfsHash: string, _name: string, _symbol: string, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DatasetPublished"
  ): TypedContractEvent<
    DatasetPublishedEvent.InputTuple,
    DatasetPublishedEvent.OutputTuple,
    DatasetPublishedEvent.OutputObject
  >;
  getEvent(
    key: "FilePurchased"
  ): TypedContractEvent<
    FilePurchasedEvent.InputTuple,
    FilePurchasedEvent.OutputTuple,
    FilePurchasedEvent.OutputObject
  >;

  filters: {
    "DatasetPublished(address,address,uint256)": TypedContractEvent<
      DatasetPublishedEvent.InputTuple,
      DatasetPublishedEvent.OutputTuple,
      DatasetPublishedEvent.OutputObject
    >;
    DatasetPublished: TypedContractEvent<
      DatasetPublishedEvent.InputTuple,
      DatasetPublishedEvent.OutputTuple,
      DatasetPublishedEvent.OutputObject
    >;

    "FilePurchased(address,string)": TypedContractEvent<
      FilePurchasedEvent.InputTuple,
      FilePurchasedEvent.OutputTuple,
      FilePurchasedEvent.OutputObject
    >;
    FilePurchased: TypedContractEvent<
      FilePurchasedEvent.InputTuple,
      FilePurchasedEvent.OutputTuple,
      FilePurchasedEvent.OutputObject
    >;
  };
}
